import {
  datesOfIsoWeek,
  isoDate,
  type MenuDay,
  type MenuItem,
  type ScheduleEntry,
} from '@piccolo/core';
import {
  and,
  asc,
  closedDates,
  customers,
  type Db,
  eq,
  inArray,
  menuItems,
  menuSchedule,
  menuWeeks,
  orderExtras,
  orderItems,
  orderMenus,
  orders,
  sql,
} from '@piccolo/db';
import { toMenuItem } from '../menu/repo';

/*
 * The submission's queries. Each request makes as few round trips as it can: the response time
 * of a submission is mostly network latency to Postgres, one round trip per statement.
 */

/** A transaction of `Db`. */
export type Tx = Parameters<Parameters<Db['transaction']>[0]>[0];

/** What deciding a submission needs from the database: one week, as it is now. */
export interface SubmissionSource {
  publishedAt: Date | null;
  /** The week's closed dates (Monday to Sunday), `YYYY-MM-DD`, ascending. */
  closedDates: string[];
  /** The week's schedule entries of the requested items. */
  schedule: ScheduleEntry[];
  /** The requested items that exist, active or not, sold out or not. */
  items: MenuItem[];
}

/**
 * Reads the week and the submission's items, in two statements. The items are locked `FOR SHARE`
 * until the transaction ends, so a sold-out switch, a price change or a menu save that touches
 * them waits for this submission instead of slipping in between the check and the write.
 */
export async function readSubmissionSource(
  tx: Tx,
  isoYear: number,
  isoWeek: number,
  itemIds: readonly string[],
  timezone: string,
): Promise<SubmissionSource> {
  const rows =
    itemIds.length === 0
      ? []
      : await tx
          .select({
            item: menuItems,
            // `null` when the item is not scheduled on the week (permanent items never are).
            scheduledId: menuSchedule.menuItemId,
            day: menuSchedule.day,
            sortOrder: menuSchedule.sortOrder,
          })
          .from(menuItems)
          .leftJoin(
            menuSchedule,
            and(
              eq(menuSchedule.menuItemId, menuItems.id),
              eq(menuSchedule.isoYear, isoYear),
              eq(menuSchedule.isoWeek, isoWeek),
            ),
          )
          .where(inArray(menuItems.id, [...itemIds]))
          // One lock order for every submission.
          .orderBy(asc(menuItems.id))
          .for('share', { of: menuItems });

  const dates = datesOfIsoWeek(isoYear, isoWeek, timezone);
  const {
    rows: [week],
  } = await tx.execute<{ published_at: Date | null; closed_dates: string[] }>(sql`
    select
      (select ${menuWeeks.publishedAt} from ${menuWeeks}
        where ${menuWeeks.isoYear} = ${isoYear} and ${menuWeeks.isoWeek} = ${isoWeek}) as published_at,
      array(select ${closedDates.date}::text from ${closedDates}
        where ${closedDates.date} between ${isoDate(dates[0])} and ${isoDate(dates[6])}
        order by 1) as closed_dates`);

  const items = new Map<string, MenuItem>();
  const schedule: ScheduleEntry[] = [];
  for (const row of rows) {
    items.set(row.item.id, toMenuItem(row.item));
    if (row.scheduledId !== null) {
      schedule.push({
        isoYear,
        isoWeek,
        // The admin routes write 1–6 or null; `buildPublicMenu` would skip any other day.
        day: row.day as MenuDay | null,
        menuItemId: row.scheduledId,
        sortOrder: row.sortOrder ?? 0,
      });
    }
  }
  return {
    publishedAt: week?.published_at ?? null,
    closedDates: week?.closed_dates ?? [],
    schedule,
    items: [...items.values()],
  };
}

/** Every row of one submission. Ids are generated by the caller, so nothing needs `RETURNING`. */
export interface SubmissionRows {
  customer: Pick<
    typeof customers.$inferInsert,
    'emailKey' | 'email' | 'name' | 'phone' | 'address'
  >;
  /** `customer_id` is the upserted customer's. */
  orders: Omit<typeof orders.$inferInsert, 'customerId'>[];
  menus: (typeof orderMenus.$inferInsert)[];
  /** At least one per menu. */
  items: (typeof orderItems.$inferInsert)[];
  extras: (typeof orderExtras.$inferInsert)[];
}

/**
 * Writes a submission in one statement, so one round trip: the customer upsert and the inserts are
 * data-modifying CTEs of a single `INSERT`. Postgres runs every CTE to completion and checks the
 * foreign keys at the end of the statement, when all the rows exist.
 *
 * The customer is keyed by `email_key` and takes the submission's e-mail, name, phone and address
 * and `last_order_at`; an empty address (pickup only) keeps the stored one.
 */
export async function writeSubmission(tx: Tx, rows: SubmissionRows): Promise<void> {
  const customer = tx.$with('customer').as(
    tx
      .insert(customers)
      .values({ ...rows.customer, lastOrderAt: sql`now()` })
      .onConflictDoUpdate({
        target: customers.emailKey,
        set: {
          email: sql`excluded.email`,
          name: sql`excluded.name`,
          phone: sql`excluded.phone`,
          address: sql`case when excluded.address = '' then ${customers.address} else excluded.address end`,
          lastOrderAt: sql`excluded.last_order_at`,
          updatedAt: sql`now()`,
        },
      })
      .returning({ id: customers.id }),
  );
  const customerId = sql`(select ${customer.id} from ${customer})`;

  const newOrders = tx.$with('new_orders').as(
    tx
      .insert(orders)
      .values(rows.orders.map((order) => ({ ...order, customerId })))
      .returning({ id: orders.id }),
  );
  const newMenus = tx
    .$with('new_menus')
    .as(tx.insert(orderMenus).values(rows.menus).returning({ id: orderMenus.id }));

  if (rows.extras.length === 0) {
    await tx.with(customer, newOrders, newMenus).insert(orderItems).values(rows.items);
    return;
  }
  const newItems = tx
    .$with('new_items')
    .as(tx.insert(orderItems).values(rows.items).returning({ id: orderItems.id }));
  await tx.with(customer, newOrders, newMenus, newItems).insert(orderExtras).values(rows.extras);
}
